---
name: CI Tests

on: 
  workflow_dispatch:
    branches: [ develop,feature/ci-actions ]
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop, feature/ci-actions ]

  
jobs:
  test-affected:
    uses: ./.github/workflows/nxtest.yml
    with:
      test: 'affected'

  test-all:
    uses: ./.github/workflows/nxtest.yml
    with:
      test: 'all'