---
name: 'Default Test'

# Reusable workflow 
on:
  workflow_call:
    inputs:
      test:
        description: 'Type of test being run'
        required: true
        type: string
      branch:
        description: 'Branch to use as base'
        required: false
        type: string

jobs:
  build:
    name: Generate cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'develop'

      - name: Cache node modules
        id: dependency_cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'